version: '2'
services:
  agilemind-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/AgileMind/postgresql/:/var/lib/postgresql/data/
      - ~/volumes/jhipster/AgileMind/backups/:/opt/
    environment:
      - POSTGRES_USER=agilemind
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
